[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd cot-backend && npm ci",
  "cd cot-frontend && npm ci"
]

[phases.build]
cmds = [
  "cd cot-backend && npm run build",
  "cd cot-frontend && npm run build"
]

[start]
cmd = "cd cot-backend && node dist/server.js"
